# Generated by Django 5.0.6 on 2024-07-14 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='cours',
        ),
    ]
