# Generated by Django 5.0.6 on 2024-07-15 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscription_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cours_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
