# Generated by Django 4.2.13 on 2024-06-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=0, help_text='nombre de minutes maximal pour remplir le quiz'),
            preserve_default=False,
        ),
    ]
