# Generated by Django 5.0.6 on 2024-07-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_quiz_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Evaluation'},
        ),
    ]
