# Generated by Django 5.0.6 on 2024-05-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_miniapp_cours'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='media.pdfs/'),
        ),
        migrations.AddField(
            model_name='cours',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
