# Generated by Django 5.0.6 on 2024-06-20 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_cours_pdf_cours_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='classe',
            field=models.ManyToManyField(related_name='matieres', to='posts.classe'),
        ),
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.classe')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.matiere')),
            ],
        ),
        migrations.AddField(
            model_name='cours',
            name='chapitre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.chapitre'),
        ),
    ]
