# Generated by Django 5.0.6 on 2024-06-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_matiere_classe_chapitre_cours_chapitre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='chapitre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.chapitre'),
        ),
    ]
