# Generated by Django 5.0.6 on 2024-07-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_chapitre_create_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapitre',
            name='create_on',
        ),
    ]
