# Generated by Django 5.0.6 on 2024-07-09 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_chapitre_create_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapitre',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
    ]
