# Generated by Django 5.0.6 on 2024-07-15 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_cours_pdf_alter_cours_video'),
        ('quizes', '0004_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quizes.quiz'),
        ),
    ]
